namespace:
  create: true

image:
  repository: ghcr.io/kroy-the-rabbit/authvector
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 2

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

viewStore:
  mode: crd

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

podSecurityContext: {}

containerSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 10001
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

probes:
  readiness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 20

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    use-forwarded-headers: "true"
    forwarded-for-header: "CF-Connecting-IP"
  host: authvector.lan.kroy.io
  tls:
    secretName: authvector-lan-kroy-io
